### ISSUE TITLE
Inconsistent version of dependencies between `build.ver` and `run.ver`

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/obsproc#20]
The version on libraries between `build.ver` and `run.ver` are inconsistent.

Note, none of the obsproc code now depends on `w3nco`.  They only depend on `w3emc`.

Here is a snapshot of `build.ver` and `run.ver` from `develop` at bd4211a.

```
$> cat build.ver
export hdf5_ver=1.10.6
export netcdf_ver=4.7.4
export bacio_ver=2.4.1
export w3emc_ver=2.9.1
export sp_ver=2.3.3
export sigio_ver=2.3.2
export nemsio_ver=2.5.2
export bufr_ver=11.5.0
```

```
$> cat run.ver
#########################################
#Export module version numbers
#########################################

export prod_util_ver=2.0.8
export prod_envir_ver=2.0.5

export grib_util_ver=1.2.2
export util_shared_ver=1.4.0
export hdf5_ver=1.10.6
export netcdf_ver=4.7.4
export w3nco_ver=2.4.1
export w3emc_ver=2.7.3
export bacio_ver=2.4.1
export bufr_dump_ver=1.0.0
export bufr_ver=11.5.0

export envvar_ver=1.0
export PrgEnv_intel_ver=8.1.0
export intel_ver=19.1.3.304
export craype_ver=2.7.8
export cray_mpich_ver=8.1.7
export cray_pals_ver=1.0.12
export cfp_ver=2.0.4

export gfs_ver=v16.2
export dictionaries_ver=v3.4.0
export omb_ver=v4.4

export PROCESS_MASTER_SHIP_STNLIST=NO
export BACK=off
```

Also, note that all NCEPLibs are built as static libraries, and linked statically in the obsproc codes, so it is very likely these libraries don't need to be loaded at runtime.

At a bare minimum, the library versions in `build.ver` and `run.ver` need to be consistent.

See the [satingest](https://github.com/NOAA-EMC/satingest) repository, since it does this better.

**Comment by ShelleyMelchior-NOAA** [comment]
Will be reconciling this soon as iterations with NCO continue to refine.

**Comment by ShelleyMelchior-NOAA** [comment]
`run.ver` and `build.ver` files are now reconciled with NCO in `release/obsproc.v1.0.0`.
