### ISSUE TITLE
release/obsproc.v1.0.0 build errors on Hera and Orion

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/obsproc#24]
I need to install the new WCOSS2 obsproc package (`release/obsproc.v1.0.0`) on Hera and Orion to support users running the new GFSv16.2.0 package there (and WCOSS2 in global space eventually too). I tried to build the `release/obsproc.v1.0.0` branch on Hera/Orion and encountered issues on both. I ran the build script like this while under the build-obsproc folder:

```
INSTALL_TARGET=orion ./build.sh
```

Is that the correct way to build on Orion (and Hera with INSTALL_TARGET=hera)?

I made a couple changes on both Hera and Orion to get the modules loaded (nemsio wasn't loading) but am hitting a compilation errors on both machines still. See the changes I made on Orion (similar changes needed for Hera) and the errors below.

Changed `module reset` to `module purge` (`module reset` only works on WCOSS2, need a purge elsewhere) and added missing `load("hpc-impi/2018.4")` in `obsproc_orion.lua` to get nemsio loading:
```
Orion-login-1[68] /work/noaa/global/kfriedma/git/obsproc/obsproc.v1.0.0$ git diff
diff --git a/build-obsproc/build.sh b/build-obsproc/build.sh
index d496380..476f791 100755
--- a/build-obsproc/build.sh
+++ b/build-obsproc/build.sh
@@ -13,7 +13,8 @@ target=$(echo $INSTALL_TARGET | tr [:upper:] [:lower:])
 if [[ "$target" =~ ^(wcoss2|hera|orion)$ ]]; then
   source $pkg_root/versions/build.ver
   set +x
-  module reset
+  #module reset
+  module purge
   module use $pkg_root/modulefiles
   module load obsproc_$target
   module list
diff --git a/modulefiles/obsproc_orion.lua b/modulefiles/obsproc_orion.lua
index 093e5c7..81741e1 100644
--- a/modulefiles/obsproc_orion.lua
+++ b/modulefiles/obsproc_orion.lua
@@ -7,6 +7,7 @@ load("cmake/3.18.1")
 prepend_path("MODULEPATH", "/apps/contrib/NCEP/libs/hpc-stack/modulefiles/stack")
 load("hpc/1.1.0")
 load("hpc-intel/2018.4")
+load("hpc-impi/2018.4")
```

I had to also add the missing `hpc-impi/2018.0.4` module load in `obsproc_hera.lua`.

Part of the error I am seeing on Orion is:
```
/work/noaa/global/kfriedma/git/obsproc/obsproc.v1.0.0/sorc/prepobs_oiqcbufr.fd/oiqcbufr.f(175): error #5102: Cannot open include file 'mpif.h'
      include "mpif.h"
--------------^
```
Here is a log with the Orion build output:
/work/noaa/global/kfriedma/git/obsproc/obsproc.v1.0.0/build-obsproc/build.log

Here is a log with the Hera build output (different error):
/scratch1/NCEPDEV/global/Kate.Friedman/git/obsproc/obsproc.v1.0.0/build-obsproc/build.log

**Comment by ShelleyMelchior-NOAA** [comment]
The build instructions are in the readme shown below the repo file listings: https://github.com/NOAA-EMC/obsproc/tree/release/obsproc.v1.0.0 or available in the docs/ dir. https://github.com/NOAA-EMC/obsproc/blob/c8a3ed201cbd59a4c109fd6a7fd87763842989d8/docs/README.md
I cannot vouch for their validity on any non-wcosss2 platform, though.

**Comment by kgerheiser** [comment]
I will look into this and get the script to build on Orion, Hera, and WCOSS2.

**Comment by kgerheiser** [comment]
Fixed with #26 

```
INSTLL_TARGET=hera INSTALL_PREFIX=install [MODULEFILE_INSTALL_PREFIX=install] ./build.sh`
```

**Comment by KateFriedman-NOAA** [comment]
> Fixed with #26

Thanks @kgerheiser ! Will these updates make their way into the `release/obsproc.v1.0.0` branch too?

**Comment by kgerheiser** [comment]
I'm not sure how branches/versions are handled with this repo. My fix was merged into `feature/rm-prep`. I can take a look at `release/obsproc.v1.0.0`.

**Comment by ShelleyMelchior-NOAA** [comment]
Yes, feature/rm-prep was made from release/obsproc.v1.0.0. We will get
feature/rm-prep merged back into release/obsproc.v1.0.0 once we are done
iterating w/ NCO about the prepobs module.

--

Shelley Melchior

I.M. Systems Group, Program Manager, Hurricane Supplemental

NOAA/NWS/NCEP/EMC

301-323-8292 (mobile/SMS)

***@***.***

**Comment by ShelleyMelchior-NOAA** [comment]
Please leave release/obsproc.v1.0.0 alone for now. That branch will be changing a lot once once feature/rm-prep is finalized w/ local testing and  NCO iterations.

**Comment by KateFriedman-NOAA** [comment]
Got it, thanks for the clarification @ShelleyMelchior-NOAA ! No need to add updates to `release/obsproc.v1.0.0` then since they will come in when `feature/rm-prep` gets merged in, thanks again @kgerheiser !

**Comment by KateFriedman-NOAA** [comment]
If folks don't object, please leave this issue open until `feature/rm-prep` gets merged in and `release/obsproc.v1.0.0` can build out of the box on Hera/Orion/WCOSS2. Thanks!

**Comment by ShelleyMelchior-NOAA** [comment]
Sure thing! Should be soonish ... next few weeks.

**Comment by KateFriedman-NOAA** [comment]
> Sure thing! Should be soonish ... next few weeks.

Awesome, thanks @ShelleyMelchior-NOAA !

**Comment by ShelleyMelchior-NOAA** [comment]
@KateFriedman-NOAA  -- `release/obsproc.v1.0.0` from obsproc github repo and `release/prepobs.v1.0.0` from prepobs github repo are now all up to date, merged, and handed off to NCO SPA Xiaoxue. When you are comfortable you may close this ticket.

**Comment by KateFriedman-NOAA** [comment]
I successfully built both packages on WCOSS2, Hera, and Orion out of the box. I am comfortable closing this ticket now. I will open a new ticket if I encounter any issues trying to run the packages within the GFS via rocoto on any of those three machines. Thanks all!
