### ISSUE TITLE
Tidy up /obsproc/triggers

### ISSUE THREAD

**Issue by ilianagenkova** [NOAA-EMC/obsproc#40]
See comments in PR [#39](https://github.com/NOAA-EMC/obsproc/pull/39) for instructions and clean up /obsproc/triggers in obsproc's first update post-WCOSS2 go-live

**Comment by ShelleyMelchior-NOAA** [comment]
The line to export obsproc_ver is set manually, not from reading any external file. This setting should always be the latest operational installation in $PACKAGEROOT if one is intending to run w/ operational code installed in $HOMEobsproc. 

A suggested change in all trigger scripts is to improve the obsproc_ver_pckg definition line to something like the following:

`export obsproc_ver_pckg=1.0.0 # check to set to latest operational installation in $PACKAGEROOT`

You can see more discussion in PR #41.
