### ISSUE TITLE
disable SYNDATA in nam_prep processing

### ISSUE THREAD

**Issue by ShelleyMelchior-NOAA** [NOAA-EMC/obsproc#42]
nam_prep processing has not been properly finding tcvitals files to run the syndat_syndata exec in operations for **quite some time** ... likely back to GFSv15 days, when the com dir structure for GFS did not include $COMPONENT and $cyc.  NAM is at end of life and it is not worth trying to restore the SYNDATA processing, especially given that it hasn't been functioning for the better part of 2 years and no one ever knew.

NCO made some changes for WCOSS2 go-live to nam_prep processing to prevent script failure relating to unknown variable definitions. Those changes can be retained. But a better method to prevent failure is to prevent the set up to run syndat_syndata altogether.

`jobs/JOBSPROC_NAM_PREP` should be modified so that SYNDATA defaults to NO.
Line 292 should be changed to this:
`export SYNDATA=${SYNDATA:-NO}   # NEVER execute program SYNDAT_SYNDATA`

**Note1:** while $COMINtcvital and $COMSPtcvital are defined in `jobs/JOBSPROC_NAM_PREP` and `scripts/exnam_makeprepbufr.sh`, they will never lead the processing to finding the tcvitals files. Those files only reside in the gfs and gdas com, not nam com. So even if SYNDATA accidentally is set to YES, the processing will never find the required tcvitals files w/ the current path variable definitions, which leads to syndat_syndata not being executed. I mention this only to say that one could correct $COMINtcvital to point to the correct path, but that would require pointing to gfs com and a can of worms not worth opening.

**Note2:** Another approach can be to exclude the $COMINtcvital and $COMSPtcvital definitions altogether. They are not needed when SYNDATA=NO. This will then allow `versions/run.ver` to have the nam_ver dependency removed. 
imo, this is the cleanest approach ... remove $COMINtcvital from `jobs/JOBSPROC_NAM_PREP`,  remove $COMSPtcvital from `scripts/exnam_makeprepbufr.sh`, and remove nam_ver from `versions/run.ver`.

**To test** run nam_prep trigger pointing to modified obsproc codes noted above. COMIN can point to production dump files. Look for the following things in the \*.o\* log file:
- normal completion
- SYNDATA=NO

The resultant prepbufr file should have no SYNDAT item when binv.x is run on it.

Direct questions to @ShelleyMelchior-NOAA

**Comment by ilianagenkova** [comment]
@ShelleyMelchior-NOAA , is modifying _jobs/JOBSPROC_NAM_PREP_ all there is to do? 
export SYNDATA=${SYNDATA:-NO} # NEVER execute program SYNDAT_SYNDATA

**Comment by ShelleyMelchior-NOAA** [comment]
Yes, that is the minimum. You can also consider the note #2, but it is not required.

**Comment by ilianagenkova** [comment]
Suggested changes made in feature/rel.obs.v1.1.0_SYNDAT_nap_prep including everything in Note2. PR will be issues shortly.
