### ISSUE TITLE
correct JOBSPROC_AIRNOW_DUMP for non-NCO user

### ISSUE THREAD

**Issue by ShelleyMelchior-NOAA** [NOAA-EMC/obsproc#47]
In helping to get airnow processing running correctly on WCOSS2, it was discovered that airnow processing has a different bug when run by a non-NCO user.

Lines 215 and 286 of JOBSPROC_AIRNOW_DUMP need to be modified to *not* inherit the previous definition for COMIN.
Change from
`export COMIN=${COMIN:-${COMIN_ROOT:?}/${obsNET}/${obsproc_ver}/${model}.${pdy}}`
to
`export COMIN=${COMIN_ROOT:?}/${obsNET}/${obsproc_ver}/${model}.${pdy}`

Target this change to be included in the first obsproc upgrade following go-live.
This bug only impacts dev (non-NCO) users and so is not impactful to operations, but may impact development and check out.

**Comment by ShelleyMelchior-NOAA** [comment]
New feature branch created: **feature/airnow4devuser**

parent branch is release/obsproc.v1.0.0

**Comment by ilianagenkova** [comment]
Looks like you have a branch for this. Could you open a PR, pls, thanks!

**Comment by ShelleyMelchior-NOAA** [comment]
Ok, yes, let's PR this for release/obsproc.v1.1.0

**Comment by ilianagenkova** [comment]
This changes are now in release/obsproc.v1.1.0
