### ISSUE TITLE
RTMA_RU 0000Z Cycle Failure

### ISSUE THREAD

**Issue by PraveenKumar-NOAA** [NOAA-EMC/obsproc#80]
- The RTMA_RU 0000Z cycle was failing intermittently when trying to read from a malformed ADPSFC BUFR tank, essentially owing to some read-write interference. The obsproc_rtma code was fixed with a temporary trap to prevent this clash from occurring. 

- The purpose of this issue is to explore a robust fix and integrate it into the existing RTMA codes.

Notes and old work history: 

- https://vlab.noaa.gov/redmine/issues/70153
- https://vlab.noaa.gov/redmine/issues/73355
- https://vlab.noaa.gov/redmine/issues/75717

Proposed plan: 

- Disable the bug-fix and set an end-to-end cron to allow 8 minutes of processing
- Check output WCOSS2 data

**Comment by PraveenKumar-NOAA** [comment]
Test jobs were run on WCOSS2 for the RTMA and RTMA_RU. 

Disabled the bug-fix into the exrtma_dump.sh file and cron were set up to allow end-to-end 8 minutes of processing for the RTMA_RU 0000Z cycle.

**Comment by PraveenKumar-NOAA** [comment]
CRON is running well for the last two days, without any failure.

**Comment by PraveenKumar-NOAA** [comment]
The fix was enabled and DTIM_latest_000000 was changed from -0.01 to 0.5. There is only one adpsfc subset, 0000000 in the exrtma_dump.sh file. CRON is running and generating the data files.

**Comment by PraveenKumar-NOAA** [comment]
@ilianagenkova I inspected my cron runs and compared them with the $COMROOT for the sizes, and number of *.bufr_d, *.nr, *.listing, *prepbufr* files. For some cycles like 20230402, there was no difference. But I observed some failures in 20230403 DUMP and PREP_POST jobs due to the memory and walltime restrictions. I increased these values in my trigger scripts for future runs. I will keep you posted.

**Comment by PraveenKumar-NOAA** [comment]
@ilianagenkova do you want me to close this issue?

**Comment by ilianagenkova** [comment]
Para runs showed that there are enough instances where the  rtma_ru 0000z with DTIM_latest_000000 = 0.5 is looking for adpsfc tanks that are not yet available. Thus crashing the code. Therefore, code was reverted to DTIM_latest_000000 =  -0.01 .
