### ISSUE TITLE
Trigger and job scripts for the Marine and Aerosol data

### ISSUE THREAD

**Issue by PraveenKumar-NOAA** [NOAA-EMC/obsproc#87]
The aim of this issue is to write the trigger and job scripts for the following two data-types: 

**Marine data (/ocean):**
- trigger script -  **_jglobal_ocean.wc2.pbs_** 
- job script - **_JOBSPROC_GLOBAL_OCEAN_**

**Aerosol data (/chem):** 
- trigger script - **_jglobal_chem.wc2.pbs_**
- job script - **_JOBSPROC_GLOBAL_CHEM_**

To test these scripts, a dummy text file, ocean.txt or chem.txt will be written into the output $COMROOT/obsproc/v1.2/gfs.20240625/00/ocean/* or $COMROOT/obsproc/v1.2/gfs.20240625/00/chem/*, respectively.

The progress will be recorded into the feature/ocean_praveen branch.

**Comment by PraveenKumar-NOAA** [comment]
@ilianagenkova I finished these scripts for the marine and aerosol data, and added to the feature/ocean_praveen branch. Please have a look, when you have time

**Comment by ilianagenkova** [comment]
@PraveenKumar-NOAA , replace the calls to **exglobal_dump.sh** in the new jobs with calls to "test_ocean.sh" / "test_chem.sh" where test_*.sh  is simply:

#!/bin/sh
echo "HELLO OCEAN/CHEM"

and then test the branch in its entirety , from the command line, with what I imagine would be:
jtyp=gdas/gfs cyc=00 PDY=20240711 desc=ocean_test bash -l /u/iliana.genkova/bin/cycqsub  /path/to/jglobal_ocean.wc2.pbs

These jobs will run for gdas and gfs cycles, but will write out into $COMROOT/obsproc/v*.*/gdas[gfs].YYYYMMHH/CC/**ocean**/

**Comment by PraveenKumar-NOAA** [comment]
@ilianagenkova done, thanks! Ran and tested successfully on Dogwood.

**Comment by ilianagenkova** [comment]
[dlogin07 /lfs/h2/emc/stmp/praveen.singh/CRON]$ more Test-Ocean/com/obsproc/v1.0/gdas.20240705/00/ocean/ocean.txt                                                     
Ocean group thread executed.
[dlogin07 /lfs/h2/emc/stmp/praveen.singh/CRON]$ more  Test-Chem/com/obsproc/v1.0/gdas.20240705/00/chem/chem.txt                                                        
Chem group thread executed.

It looks like
https://github.com/NOAA-EMC/obsproc/tree/feature/ocean_praveen
is doing what it's supposed to.  Thanks, @PraveenKumar-NOAA !

 I will close this issue and let you know if/when I have any questions when merging this code into the next release.
