### ISSUE TITLE
Update obsproc build for RDHPCS spack-stack and Rocky OS

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/obsproc#88]
Update the obsproc build to support RDHPCS spack-stack libraries and the new Rocky8/9 OS upgrades. This is similar to updates made to the prepobs package recently.

Also add support to new MSU Hercules platform (attached to MSU Orion).

Maintain current functionality for WCOSS2 build.

**Comment by KateFriedman-NOAA** [comment]
Created new `dev/gfsv17` branch to hold these changes outside of the `develop` branch.

**Comment by KateFriedman-NOAA** [comment]
FYI @DavidBurrows-NCO - I am now updating a branch of obsproc to support RDHPCS spack-stack and Rocky8/9. We don't currently use execs from obsproc but we should have a fully built package on the R&Ds when we use scripts from it. With this work I am updating us to obsproc/v1.2. FYI for your work on Gaea.

**Comment by KateFriedman-NOAA** [comment]
@ilianagenkova While testing my updated branch on WCOSS2-Cactus I encountered an issue loading some of the modules when the `module purge` command was run during build. If I don't do `module purge` then I have no issues and the build succeeds. I notice that the `develop` branch `ush/build.sh` does not currently do a `module purge` (or `module reset`). Have you encountered this issue on WCOSS2 as well? Is there a reason that the obsproc build does not purge or reset modules?

Here are two logs from my build on Cactus, one with `module purge` (which fails) and one without (which succeeds):
```
/lfs/h2/emc/global/noscrub/kate.friedman/git/obsproc/dev-gfsv17/ush/log.purge
/lfs/h2/emc/global/noscrub/kate.friedman/git/obsproc/dev-gfsv17/ush/log.no_purge
```

**Comment by ilianagenkova** [comment]
All of us in ObsProc have certain modules loaded with .bashrc - they say it's a bad practice, but w.out them we can't do anything (command line, scripts, etc.) B/c of that I can't give you a 100% clear answer, but yes, when I 'module purge' in the obsproc triggers before loading the required modules, the system isn't happy. Haven't had time to investigate.

**Comment by DavidBurrows-NCO** [comment]
@KateFriedman-NOAA Thanks for the information...I am at the UIFCW conference this week and on PTO the following week..I return 8/5 and will get back to this work then.

**Comment by KateFriedman-NOAA** [comment]
@DavidBurrows-NCO Sounds good, no rush and enjoy your leave! :)

**Comment by aerorahul** [comment]
@KateFriedman-NOAA 
If you do a `module purge` in `ush/build.sh`, you will also need to uncomment `--load(envvar)` in `modulefiles/obsproc_wcoss2.lua`.  Doing so, will allow you to build on wcoss2 with a `module purge`.

**Comment by aerorahul** [comment]
@KateFriedman-NOAA See #91

**Comment by KateFriedman-NOAA** [comment]
Work complete, PR merged, `obsproc.v1.2.0-rd-gfsv17` tag cut. Installing on supported platforms. Closing.
