### ISSUE TITLE
Setup obsproc to compile and run C96_atm3DVar CI test on Gaea-C5

### ISSUE THREAD

**Issue by DavidBurrows-NCO** [NOAA-EMC/obsproc#94]
Update build file and add Gaea-specific module files to compile and run obsproc for C96_atm3DVar global-workflow CI experiment on Gaea-C5

Refs NOAA-EMC/global-workflow [#2766](https://github.com/NOAA-EMC/global-workflow/issues/2766)

**Comment by aerorahul** [comment]
closed via #95
